version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: real_estate_search_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./RealEstateSearch:/app
    ports:
      - 8000:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env/.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env/.env

  redis:
    restart: unless-stopped
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: real_estate_search_worker
    command: /start-celeryworker
    volumes:
      - ./RealEstateSearch:/app
    env_file:
      - ./.env/.env
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: real_estate_search_celery_beat
    command: /start-celerybeat
    volumes:
      - ./RealEstateSearch:/app
    env_file:
      - ./.env/.env
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: real_estate_search_celery_flower
    command: /start-flower
    volumes:
      - ./RealEstateSearch:/app
    env_file:
      - ./.env/.env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: