# Generated by Django 4.1.6 on 2023-03-07 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', max_length=100)),
                ('cityName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchingSettingCategory', to='olxSearch.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchingSettingCity', to='olxSearch.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advId', models.IntegerField(default=0)),
                ('link', models.CharField(default='#', max_length=200)),
                ('pic', models.CharField(default='', max_length=300)),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0.0)),
                ('date_published', models.CharField(default='', max_length=50)),
                ('area', models.FloatField(default=0.0)),
                ('rooms', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realEstateCategory', to='olxSearch.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realEstateCity', to='olxSearch.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
