# Generated by Django 4.1.6 on 2023-03-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTagsNameToFind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portalName', models.CharField(default='', max_length=50)),
                ('values', models.TextField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HtmlTagsNameToFindCategory', to='olxSearch.category')),
            ],
        ),
    ]
