# Generated by Django 4.1.3 on 2022-11-29 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olxSearch', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('typ', models.CharField(choices=[('mieszkania', 'Mieszkania'), ('działki', 'Dziłki'), ('domy', 'Domy')], default='mieszkania', max_length=20)),
                ('rooms', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsersSearchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchSetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchSet', to='olxSearch.searchset')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSearchSet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
