# Generated by Django 4.1.3 on 2022-11-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olxSearch', '0003_searchset_userssearchset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('mieszkania', 'Mieszkania'), ('działki', 'Dziłki'), ('domy', 'Domy')], default='mieszkania', max_length=20)),
                ('rooms', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='userssearchset',
            name='searchSetId',
        ),
        migrations.RemoveField(
            model_name='userssearchset',
            name='userId',
        ),
        migrations.DeleteModel(
            name='SearchSet',
        ),
        migrations.DeleteModel(
            name='UsersSearchSet',
        ),
    ]
