# Generated by Django 4.1.3 on 2022-12-03 12:11

from django.db import migrations, models
import olxSearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0005_remove_searchingsettings_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='searchingsettings',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name=olxSearch.models.City),
        ),
    ]
