# Generated by Django 4.1.6 on 2023-03-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0005_alter_apartment_buildingtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HtmlTagsNameToFind',
        ),
    ]
