<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-04-07 17:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("olxSearch", "0006_delete_htmltagsnametofind"),
=======
# Generated by Django 4.1.6 on 2023-04-09 20:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0006_delete_htmltagsnametofind'),
>>>>>>> aae4168 (added-first-tests)
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="apartment",
            name="area",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="price",
            field=models.FloatField(
                default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="searchingsettings",
            name="area",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="searchingsettings",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Date of created SearchSettings",
            ),
        ),
        migrations.AlterField(
            model_name="searchingsettings",
            name="rooms",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
=======
            model_name='apartment',
            name='area',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='searchingsettings',
            name='area',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='searchingsettings',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 20, 42, 58, 319249), verbose_name='Date of created SearchSettings'),
        ),
        migrations.AlterField(
            model_name='searchingsettings',
            name='rooms',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
>>>>>>> aae4168 (added-first-tests)
        ),
    ]
