# Generated by Django 4.1.3 on 2022-12-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0007_alter_searchingsettings_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchingsettings',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='olxSearch.city'),
        ),
    ]
