# Generated by Django 4.1.6 on 2023-04-12 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0007_alter_apartment_area_alter_apartment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchingsettings',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 12, 16, 17, 23, 253875), verbose_name='Date of created SearchSettings'),
        ),
    ]
