# Generated by Django 4.1.6 on 2023-04-16 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olxSearch", "0009_alter_searchingsettings_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchingsettings",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 16, 15, 51, 12, 790915),
                verbose_name="Date of created SearchSettings",
            ),
        ),
    ]
