# Generated by Django 4.1.3 on 2022-12-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0009_city_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='RealEstateCities', to='olxSearch.city'),
        ),
    ]
