# Generated by Django 4.1.3 on 2022-12-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0011_alter_apartment_category_alter_apartment_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='category',
            field=models.IntegerField(choices=[(0, 'mieszkania'), (1, 'dziłki'), (2, 'domy')], default=0),
        ),
        migrations.AlterField(
            model_name='searchingsettings',
            name='category',
            field=models.IntegerField(choices=[(0, 'mieszkania'), (1, 'dziłki'), (2, 'domy')], default=0),
        ),
    ]
