# Generated by Django 4.1.6 on 2023-04-17 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("olxSearch", "0021_alter_searchingsettings_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="date_published2",
        ),
        migrations.AddField(
            model_name="searchingsettings",
            name="buildingType",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="searchingSettingsBuildingType",
                to="olxSearch.buildingtype",
            ),
        ),
        migrations.AlterField(
            model_name="searchingsettings",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 17, 14, 40, 18, 130886),
                verbose_name="Date of created SearchSettings",
            ),
        ),
    ]
