# Generated by Django 4.1.6 on 2023-04-17 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("olxSearch", "0022_remove_apartment_date_published2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchingsettings",
            name="date_created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Date of created SearchSettings",
            ),
        ),
    ]
