# Generated by Django 4.1.6 on 2023-04-18 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("olxSearch", "0023_alter_searchingsettings_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchingsettings",
            name="area",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="searchingsettings",
            name="rooms",
            field=models.IntegerField(
                blank=True,
                default=1,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
