# Generated by Django 4.1.3 on 2022-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advId', models.IntegerField(default=0)),
                ('link', models.CharField(default='#', max_length=200)),
                ('pic', models.CharField(default='', max_length=300)),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('date_published', models.CharField(default='', max_length=50)),
                ('area', models.FloatField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('rooms', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
