# Generated by Django 4.1.3 on 2022-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olxSearch', '0004_searchingsettings_remove_userssearchset_searchsetid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchingsettings',
            name='type',
        ),
        migrations.AddField(
            model_name='searchingsettings',
            name='category',
            field=models.CharField(choices=[('mieszkania', 'Mieszkania'), ('działki', 'Dziłki'), ('domy', 'Domy')], default='Mieszkania', max_length=20),
        ),
    ]
